import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 9,
  tables: [
    tableSchema({
      name: 'patients',
      columns: [
        { name: 'remote_id', type: 'string', isIndexed: true },
        { name: 'first_name', type: 'string' },
        { name: 'last_name', type: 'string' },
        { name: 'date_of_birth', type: 'number' },
        { name: 'phone', type: 'string', isOptional: true },
        { name: 'email', type: 'string', isOptional: true },
        { name: 'medical_notes', type: 'string', isOptional: true },
        { name: 'is_synced', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'sessions',
      columns: [
        { name: 'remote_id', type: 'string', isIndexed: true },
        { name: 'patient_id', type: 'string', isIndexed: true },
        { name: 'therapist_id', type: 'string', isIndexed: true },
        { name: 'scheduled_at', type: 'number', isIndexed: true },
        { name: 'duration_minutes', type: 'number' },
        { name: 'status', type: 'string' },
        { name: 'session_type', type: 'string' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'pain_level_before', type: 'number', isOptional: true },
        { name: 'pain_level_after', type: 'number', isOptional: true },
        { name: 'pain_locations', type: 'string', isOptional: true },
        { name: 'is_synced', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'checklist_items',
      columns: [
        { name: 'remote_id', type: 'string', isIndexed: true },
        { name: 'session_id', type: 'string', isIndexed: true },
        { name: 'title', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'is_completed', type: 'boolean' },
        { name: 'completed_at', type: 'number', isOptional: true },
        { name: 'sort_order', type: 'number' },
        { name: 'is_synced', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'insurance_cards',
      columns: [
        { name: 'remote_id', type: 'string', isIndexed: true },
        { name: 'patient_id', type: 'string', isIndexed: true },
        { name: 'bhyt_card_number', type: 'string', isIndexed: true },
        { name: 'bhyt_prefix_code', type: 'string' },
        { name: 'bhyt_coverage_percent', type: 'number' },
        { name: 'bhyt_copay_rate', type: 'number' },
        { name: 'hospital_registration_code', type: 'string', isOptional: true },
        { name: 'expiration_date', type: 'number', isOptional: true },
        { name: 'valid_from', type: 'number' },
        { name: 'valid_to', type: 'number' },
        { name: 'is_verified', type: 'boolean' },
        { name: 'version', type: 'number' },
        { name: 'is_synced', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'outcome_measures',
      columns: [
        { name: 'remote_id', type: 'string', isIndexed: true },
        { name: 'patient_id', type: 'string', isIndexed: true },
        { name: 'measure_type', type: 'string', isIndexed: true },
        { name: 'baseline_score', type: 'number' },
        { name: 'current_score', type: 'number' },
        { name: 'target_score', type: 'number' },
        { name: 'measurement_date', type: 'number' },
        { name: 'mcid_threshold', type: 'number' },
        { name: 'phase', type: 'string' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'version', type: 'number' },
        { name: 'is_synced', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'invoices',
      columns: [
        { name: 'remote_id', type: 'string', isIndexed: true },
        { name: 'patient_id', type: 'string', isIndexed: true },
        { name: 'invoice_number', type: 'string', isIndexed: true },
        { name: 'total_amount', type: 'number' },
        { name: 'insurance_amount', type: 'number' },
        { name: 'copay_amount', type: 'number' },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'invoice_date', type: 'number' },
        { name: 'version', type: 'number' },
        { name: 'is_synced', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'invoice_items',
      columns: [
        { name: 'remote_id', type: 'string', isIndexed: true },
        { name: 'invoice_id', type: 'string', isIndexed: true },
        { name: 'service_code', type: 'string' },
        { name: 'service_name', type: 'string' },
        { name: 'quantity', type: 'number' },
        { name: 'unit_price', type: 'number' },
        { name: 'line_total', type: 'number' },
        { name: 'is_synced', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'payments',
      columns: [
        { name: 'remote_id', type: 'string', isIndexed: true },
        { name: 'invoice_id', type: 'string', isIndexed: true },
        { name: 'amount', type: 'number' },
        { name: 'payment_method', type: 'string' },
        { name: 'payment_date', type: 'number' },
        { name: 'receipt_number', type: 'string', isOptional: true },
        { name: 'version', type: 'number' },
        { name: 'is_synced', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'discharge_plans',
      columns: [
        { name: 'remote_id', type: 'string', isIndexed: true },
        { name: 'patient_id', type: 'string', isIndexed: true },
        { name: 'planned_date', type: 'number' },
        { name: 'baseline_comparison', type: 'string' },
        { name: 'outcome_trending', type: 'string' },
        { name: 'hep_exercises', type: 'string' },
        { name: 'recommendations', type: 'string', isOptional: true },
        { name: 'recommendations_vi', type: 'string', isOptional: true },
        { name: 'version', type: 'number' },
        { name: 'is_synced', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'discharge_summaries',
      columns: [
        { name: 'remote_id', type: 'string', isIndexed: true },
        { name: 'patient_id', type: 'string', isIndexed: true },
        { name: 'discharge_date', type: 'number' },
        { name: 'summary_text', type: 'string', isOptional: true },
        { name: 'summary_text_vi', type: 'string', isOptional: true },
        { name: 'final_scores', type: 'string' },
        { name: 'improvement_percent', type: 'number' },
        { name: 'follow_up_recommendations', type: 'string', isOptional: true },
        { name: 'is_synced', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'clinical_protocols',
      columns: [
        { name: 'remote_id', type: 'string', isIndexed: true },
        { name: 'protocol_name', type: 'string' },
        { name: 'protocol_name_vi', type: 'string' },
        { name: 'description', type: 'string' },
        { name: 'description_vi', type: 'string' },
        { name: 'goals', type: 'string' },
        { name: 'exercises', type: 'string' },
        { name: 'frequency', type: 'string' },
        { name: 'duration_weeks', type: 'number' },
        { name: 'progression_criteria', type: 'string' },
        { name: 'is_synced', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'patient_protocols',
      columns: [
        { name: 'remote_id', type: 'string', isIndexed: true },
        { name: 'patient_id', type: 'string', isIndexed: true },
        { name: 'protocol_id', type: 'string', isIndexed: true },
        { name: 'assigned_date', type: 'number' },
        { name: 'current_week', type: 'number' },
        { name: 'completed_exercises', type: 'string' },
        { name: 'progress_status', type: 'string' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'version', type: 'number' },
        { name: 'is_synced', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'rom_assessments',
      columns: [
        { name: 'remote_id', type: 'string', isIndexed: true },
        { name: 'patient_id', type: 'string', isIndexed: true },
        { name: 'visit_id', type: 'string', isOptional: true },
        { name: 'clinic_id', type: 'string' },
        { name: 'therapist_id', type: 'string' },
        { name: 'joint', type: 'string', isIndexed: true },
        { name: 'side', type: 'string' },
        { name: 'movement_type', type: 'string' },
        { name: 'degree', type: 'number' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'assessed_at', type: 'number', isIndexed: true },
        { name: 'is_synced', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'mmt_assessments',
      columns: [
        { name: 'remote_id', type: 'string', isIndexed: true },
        { name: 'patient_id', type: 'string', isIndexed: true },
        { name: 'visit_id', type: 'string', isOptional: true },
        { name: 'clinic_id', type: 'string' },
        { name: 'therapist_id', type: 'string' },
        { name: 'muscle_group', type: 'string', isIndexed: true },
        { name: 'side', type: 'string' },
        { name: 'grade', type: 'number' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'assessed_at', type: 'number', isIndexed: true },
        { name: 'is_synced', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'sync_queue',
      columns: [
        { name: 'entity_type', type: 'string', isIndexed: true },
        { name: 'entity_id', type: 'string' },
        { name: 'action', type: 'string' },
        { name: 'payload', type: 'string' },
        { name: 'attempts', type: 'number' },
        { name: 'last_attempt_at', type: 'number', isOptional: true },
        { name: 'error', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
      ],
    }),
  ],
});
