"use client";

import * as React from "react";
import { useState } from "react";
import {
  FileText,
  Edit3,
  Check,
  X,
  Loader2,
  Sparkles,
  ClipboardCheck,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import type { SOAPNote, GeneratedNote } from "@/types/checklist";

interface AutoGeneratedNoteProps {
  note: GeneratedNote | null;
  isLoading?: boolean;
  onUpdate: (note: Partial<SOAPNote>) => void;
  onSign: () => Promise<void>;
  isSigning?: boolean;
  disabled?: boolean;
}

interface SectionEditorProps {
  title: string;
  content: string;
  onChange: (content: string) => void;
  isEditing: boolean;
  onEditToggle: () => void;
  disabled?: boolean;
}

const SECTION_ICONS = {
  subjective: "S",
  objective: "O",
  assessment: "A",
  plan: "P",
} as const;

const SECTION_COLORS = {
  subjective: "bg-primary-100 text-primary-700",
  objective: "bg-success-100 text-success-700",
  assessment: "bg-warning-100 text-warning-700",
  plan: "bg-error-100 text-error-700",
} as const;

const SECTION_LABELS = {
  subjective: "Subjective",
  objective: "Objective",
  assessment: "Assessment",
  plan: "Plan",
} as const;

/**
 * Individual SOAP section with edit capability
 */
function SectionEditor({
  title,
  content,
  onChange,
  isEditing,
  onEditToggle,
  disabled = false,
}: SectionEditorProps) {
  const [editValue, setEditValue] = useState(content);
  const sectionKey = title.toLowerCase() as keyof typeof SECTION_ICONS;

  const handleSave = () => {
    onChange(editValue);
    onEditToggle();
  };

  const handleCancel = () => {
    setEditValue(content);
    onEditToggle();
  };

  React.useEffect(() => {
    setEditValue(content);
  }, [content]);

  return (
    <div className="space-y-2">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div
            className={cn(
              "w-8 h-8 rounded-full flex items-center justify-center font-bold text-sm",
              SECTION_COLORS[sectionKey]
            )}
          >
            {SECTION_ICONS[sectionKey]}
          </div>
          <span className="font-medium">{SECTION_LABELS[sectionKey]}</span>
        </div>

        {!disabled && (
          <div>
            {isEditing ? (
              <div className="flex gap-1">
                <Button
                  type="button"
                  variant="ghost"
                  size="sm"
                  onClick={handleCancel}
                >
                  <X className="w-4 h-4" />
                </Button>
                <Button
                  type="button"
                  variant="ghost"
                  size="sm"
                  onClick={handleSave}
                >
                  <Check className="w-4 h-4" />
                </Button>
              </div>
            ) : (
              <Button
                type="button"
                variant="ghost"
                size="sm"
                onClick={onEditToggle}
              >
                <Edit3 className="w-4 h-4" />
              </Button>
            )}
          </div>
        )}
      </div>

      {isEditing ? (
        <textarea
          value={editValue}
          onChange={(e) => setEditValue(e.target.value)}
          className="w-full min-h-[120px] p-3 rounded-lg border-2 border-primary bg-background resize-none focus:outline-none focus:ring-2 focus:ring-primary/20"
          autoFocus
        />
      ) : (
        <div
          className={cn(
            "p-3 rounded-lg bg-muted/50 text-sm whitespace-pre-wrap",
            !content && "text-muted-foreground italic"
          )}
        >
          {content || "No content generated"}
        </div>
      )}
    </div>
  );
}

/**
 * Auto-generated SOAP note preview with editing and signing capability
 */
export function AutoGeneratedNote({
  note,
  isLoading = false,
  onUpdate,
  onSign,
  isSigning = false,
  disabled = false,
}: AutoGeneratedNoteProps) {
  const [editingSections, setEditingSections] = useState<Set<string>>(
    new Set()
  );

  const toggleEditing = (section: string) => {
    setEditingSections((prev) => {
      const next = new Set(prev);
      if (next.has(section)) {
        next.delete(section);
      } else {
        next.add(section);
      }
      return next;
    });
  };

  const handleSectionChange = (section: keyof SOAPNote, content: string) => {
    onUpdate({ [section]: content });
  };

  if (isLoading) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-primary animate-pulse" />
            Generating Clinical Note...
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {["subjective", "objective", "assessment", "plan"].map((section) => (
              <div key={section} className="space-y-2">
                <div className="h-6 w-24 bg-muted animate-pulse rounded" />
                <div className="h-20 bg-muted animate-pulse rounded" />
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    );
  }

  if (!note) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="w-5 h-5" />
            Clinical Note
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="text-center py-8 text-muted-foreground">
            <FileText className="w-12 h-12 mx-auto mb-3 opacity-50" />
            <p>Complete the checklist to generate clinical note</p>
          </div>
        </CardContent>
      </Card>
    );
  }

  const isSigned = !!note.signedAt;

  return (
    <Card className={cn(isSigned && "border-success bg-success-50/30")}>
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle className="flex items-center gap-2">
            <FileText className="w-5 h-5" />
            SOAP Note
            {note.isEdited && (
              <span className="text-xs px-2 py-0.5 rounded bg-warning-100 text-warning-700">
                Edited
              </span>
            )}
          </CardTitle>

          {isSigned && (
            <div className="flex items-center gap-2 text-success-700">
              <ClipboardCheck className="w-5 h-5" />
              <span className="text-sm font-medium">Signed</span>
            </div>
          )}
        </div>
      </CardHeader>

      <CardContent className="space-y-6">
        {/* SOAP Sections */}
        <SectionEditor
          title="Subjective"
          content={note.soapNote.subjective}
          onChange={(content) => handleSectionChange("subjective", content)}
          isEditing={editingSections.has("subjective")}
          onEditToggle={() => toggleEditing("subjective")}
          disabled={disabled || isSigned}
        />

        <SectionEditor
          title="Objective"
          content={note.soapNote.objective}
          onChange={(content) => handleSectionChange("objective", content)}
          isEditing={editingSections.has("objective")}
          onEditToggle={() => toggleEditing("objective")}
          disabled={disabled || isSigned}
        />

        <SectionEditor
          title="Assessment"
          content={note.soapNote.assessment}
          onChange={(content) => handleSectionChange("assessment", content)}
          isEditing={editingSections.has("assessment")}
          onEditToggle={() => toggleEditing("assessment")}
          disabled={disabled || isSigned}
        />

        <SectionEditor
          title="Plan"
          content={note.soapNote.plan}
          onChange={(content) => handleSectionChange("plan", content)}
          isEditing={editingSections.has("plan")}
          onEditToggle={() => toggleEditing("plan")}
          disabled={disabled || isSigned}
        />

        {/* Sign button */}
        {!isSigned && (
          <div className="pt-4 border-t">
            <Button
              type="button"
              size="lg"
              className="w-full gap-2 h-14"
              onClick={onSign}
              disabled={isSigning || disabled || editingSections.size > 0}
            >
              {isSigning ? (
                <>
                  <Loader2 className="w-5 h-5 animate-spin" />
                  Signing...
                </>
              ) : (
                <>
                  <ClipboardCheck className="w-5 h-5" />
                  Sign Clinical Note
                </>
              )}
            </Button>
            <p className="text-xs text-center text-muted-foreground mt-2">
              By signing, you confirm this note accurately represents the visit
            </p>
          </div>
        )}

        {/* Signed info */}
        {isSigned && (
          <div className="pt-4 border-t text-sm text-muted-foreground">
            <p>
              Signed by {note.signedBy} on{" "}
              {new Date(note.signedAt!).toLocaleString("vi-VN")}
            </p>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
