"use client";

import * as React from "react";
import { useState, useCallback, useMemo, useEffect } from "react";
import {
  CheckCircle2,
  Loader2,
  ChevronLeft,
  AlertTriangle,
} from "lucide-react";
// cn utility imported for potential use in conditional styling
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { ChecklistSection, SectionProgressBar } from "./ChecklistSection";
import { SessionTimer } from "./SessionTimer";
import { QuickScheduleButtons } from "./QuickScheduleButtons";
import { AutoGeneratedNote } from "./AutoGeneratedNote";
import {
  useUpdateResponse,
  useCompleteChecklist,
  useChecklistProgress,
  useSessionTimer,
  useAutoSave,
  useGeneratedNote,
  useUpdateNote,
  useQuickSchedule,
} from "@/hooks/useChecklist";
import type {
  VisitChecklist as VisitChecklistType,
  ChecklistResponseValue,
} from "@/types/checklist";

interface VisitChecklistProps {
  checklist: VisitChecklistType;
  patientId: string;
  onBack?: () => void;
  onComplete?: () => void;
  quickMode?: boolean;
}

type ViewState = "checklist" | "note" | "schedule";

/**
 * Main checklist container with sections, progress, timer, and completion flow
 */
export function VisitChecklist({
  checklist,
  patientId,
  onBack,
  onComplete,
  quickMode = false,
}: VisitChecklistProps) {
  const [viewState, setViewState] = useState<ViewState>("checklist");
  const [expandedSection, setExpandedSection] = useState<string | null>(
    checklist.template.sections[0]?.id ?? null
  );
  const [localResponses, setLocalResponses] = useState(checklist.responses);
  const [scheduledDate, setScheduledDate] = useState<Date | null>(null);

  // Mutations
  const updateResponse = useUpdateResponse();
  const completeChecklist = useCompleteChecklist();
  const updateNote = useUpdateNote();

  // Timer
  const timer = useSessionTimer(
    checklist.template.targetDurationMinutes,
    checklist.elapsedSeconds,
    checklist.status === "in_progress"
  );

  // Progress calculation
  const progress = useChecklistProgress({
    ...checklist,
    responses: localResponses,
  });

  // Generated note
  const { data: generatedNote, isLoading: isNoteLoading } = useGeneratedNote(
    checklist.id
  );

  // Quick schedule
  const { scheduleFollowUp, isScheduling } = useQuickSchedule(patientId);

  // Auto-save handler
  const handleSave = useCallback(
    (itemId: string, value: ChecklistResponseValue) => {
      updateResponse.mutate({
        checklistId: checklist.id,
        itemId,
        value,
      });
    },
    [checklist.id, updateResponse]
  );

  const { queueUpdate, flushUpdates } = useAutoSave(
    checklist.id,
    handleSave,
    500
  );

  // Handle value changes with optimistic update and auto-save
  const handleValueChange = useCallback(
    (itemId: string, value: ChecklistResponseValue) => {
      // Optimistic local update
      setLocalResponses((prev) => ({
        ...prev,
        [itemId]: {
          ...prev[itemId],
          itemId,
          value,
          completedAt: new Date().toISOString(),
          autoPopulated: false,
        },
      }));

      // Queue for auto-save
      queueUpdate(itemId, value);
    },
    [queueUpdate]
  );

  // Handle section navigation
  const handleSectionClick = useCallback((sectionId: string) => {
    setExpandedSection(sectionId);
  }, []);

  // Handle completion
  const handleComplete = useCallback(async () => {
    flushUpdates();

    try {
      await completeChecklist.mutateAsync({
        checklistId: checklist.id,
        elapsedSeconds: timer.elapsedSeconds,
      });

      setViewState("note");
    } catch (error) {
      console.error("Failed to complete checklist:", error);
    }
  }, [checklist.id, timer.elapsedSeconds, completeChecklist, flushUpdates]);

  // Handle note sign
  const handleSignNote = useCallback(async () => {
    if (!generatedNote) return;

    await updateNote.mutateAsync({
      checklistId: checklist.id,
      note: { soapNote: generatedNote.soapNote },
      sign: true,
    });

    setViewState("schedule");
  }, [checklist.id, generatedNote, updateNote]);

  // Handle schedule
  const handleSchedule = useCallback(
    async (days: number, preferredTime?: string) => {
      await scheduleFollowUp(days, preferredTime);
      const date = new Date();
      date.setDate(date.getDate() + days);
      setScheduledDate(date);
    },
    [scheduleFollowUp]
  );

  // Handle final completion
  const handleFinish = useCallback(() => {
    onComplete?.();
  }, [onComplete]);

  // Sorted sections
  const sortedSections = useMemo(
    () => [...checklist.template.sections].sort((a, b) => a.order - b.order),
    [checklist.template.sections]
  );

  // Auto-expand next incomplete section
  useEffect(() => {
    if (quickMode && expandedSection) {
      const currentIndex = sortedSections.findIndex(
        (s) => s.id === expandedSection
      );
      const currentSection = sortedSections[currentIndex];

      if (currentSection) {
        const sectionProgressData = progress.sectionProgress as Record<string, { completed: number; total: number; percentage: number }>;
        const currentSectionProgress = sectionProgressData[currentSection.id];
        if (currentSectionProgress?.percentage === 100 && currentIndex < sortedSections.length - 1) {
          const nextSection = sortedSections[currentIndex + 1];
          if (nextSection) {
            setExpandedSection(nextSection.id);
          }
        }
      }
    }
  }, [localResponses, quickMode, expandedSection, sortedSections, progress.sectionProgress]);

  // Checklist view
  if (viewState === "checklist") {
    return (
      <div className="flex flex-col h-full bg-background">
        {/* Header */}
        <header className="sticky top-0 z-10 bg-background border-b px-4 py-3 space-y-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              {onBack && (
                <Button variant="ghost" size="icon" onClick={onBack}>
                  <ChevronLeft className="w-5 h-5" />
                </Button>
              )}
              <div>
                <h1 className="font-semibold">{checklist.template.name}</h1>
                <p className="text-sm text-muted-foreground">
                  {progress.completedItems} / {progress.totalItems} completed
                </p>
              </div>
            </div>

            <SessionTimer
              elapsedSeconds={timer.elapsedSeconds}
              targetSeconds={timer.targetSeconds}
              isRunning={timer.isRunning}
              isPaused={timer.isPaused}
              onPause={timer.pause}
              onResume={timer.resume}
              compact
            />
          </div>

          {/* Progress */}
          <div className="space-y-2">
            <Progress value={progress.totalProgress} className="h-2" />
            <SectionProgressBar
              sections={sortedSections}
              responses={localResponses}
              onSectionClick={handleSectionClick}
            />
          </div>
        </header>

        {/* Sections */}
        <main className="flex-1 overflow-auto px-4 py-4 space-y-3">
          {sortedSections.map((section) => (
            <ChecklistSection
              key={section.id}
              section={section}
              responses={localResponses}
              onValueChange={handleValueChange}
              isExpanded={expandedSection === section.id}
              onExpandChange={(expanded) =>
                setExpandedSection(expanded ? section.id : null)
              }
              disabled={checklist.status === "completed"}
            />
          ))}
        </main>

        {/* Footer */}
        <footer className="sticky bottom-0 bg-background border-t p-4">
          <Button
            size="lg"
            className="w-full h-14 text-lg gap-2"
            onClick={handleComplete}
            disabled={
              !progress.canComplete ||
              completeChecklist.isPending ||
              checklist.status === "completed"
            }
          >
            {completeChecklist.isPending ? (
              <>
                <Loader2 className="w-5 h-5 animate-spin" />
                Completing...
              </>
            ) : !progress.canComplete ? (
              <>
                <AlertTriangle className="w-5 h-5" />
                Complete Required Items ({progress.requiredCompleted}/
                {progress.requiredTotal})
              </>
            ) : (
              <>
                <CheckCircle2 className="w-5 h-5" />
                Complete Session
              </>
            )}
          </Button>
        </footer>
      </div>
    );
  }

  // Note view
  if (viewState === "note") {
    return (
      <div className="flex flex-col h-full bg-background">
        <header className="sticky top-0 z-10 bg-background border-b px-4 py-3">
          <div className="flex items-center gap-3">
            <Button
              variant="ghost"
              size="icon"
              onClick={() => setViewState("checklist")}
            >
              <ChevronLeft className="w-5 h-5" />
            </Button>
            <div>
              <h1 className="font-semibold">Review Clinical Note</h1>
              <p className="text-sm text-muted-foreground">
                Review and sign the generated SOAP note
              </p>
            </div>
          </div>
        </header>

        <main className="flex-1 overflow-auto p-4">
          <AutoGeneratedNote
            note={generatedNote ?? null}
            isLoading={isNoteLoading}
            onUpdate={(updates) => {
              if (generatedNote) {
                updateNote.mutate({
                  checklistId: checklist.id,
                  note: { soapNote: { ...generatedNote.soapNote, ...updates } },
                });
              }
            }}
            onSign={handleSignNote}
            isSigning={updateNote.isPending}
          />
        </main>
      </div>
    );
  }

  // Schedule view
  return (
    <div className="flex flex-col h-full bg-background">
      <header className="sticky top-0 z-10 bg-background border-b px-4 py-3">
        <div className="flex items-center gap-3">
          <Button
            variant="ghost"
            size="icon"
            onClick={() => setViewState("note")}
          >
            <ChevronLeft className="w-5 h-5" />
          </Button>
          <div>
            <h1 className="font-semibold">Schedule Follow-up</h1>
            <p className="text-sm text-muted-foreground">
              Schedule the patient's next appointment
            </p>
          </div>
        </div>
      </header>

      <main className="flex-1 overflow-auto p-4 space-y-6">
        {/* Session summary */}
        <div className="p-4 rounded-lg bg-success-50 border border-success-200">
          <div className="flex items-center gap-3">
            <CheckCircle2 className="w-8 h-8 text-success" />
            <div>
              <h2 className="font-semibold text-success-700">
                Session Completed
              </h2>
              <p className="text-sm text-success-600">
                Duration: {Math.floor(timer.elapsedSeconds / 60)} min{" "}
                {timer.elapsedSeconds % 60} sec
              </p>
            </div>
          </div>
        </div>

        {/* Quick schedule */}
        <QuickScheduleButtons
          onSchedule={handleSchedule}
          isScheduling={isScheduling}
          scheduledDate={scheduledDate}
        />
      </main>

      <footer className="sticky bottom-0 bg-background border-t p-4">
        <Button
          size="lg"
          className="w-full h-14 text-lg"
          onClick={handleFinish}
        >
          {scheduledDate ? "Done" : "Skip & Finish"}
        </Button>
      </footer>
    </div>
  );
}
